version: "3"

services:
  backend:
    build: ./flask_backend
    ports:
      - "3003:3003"

  frontend:
    platform: linux/amd64
    build: ./react_frontend
    ports:
      - "3000:3000"
    volumes:
      - /frontend/node_modules
